/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as EnskripsyonRouteImport } from './routes/enskripsyon'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppEstokRouteImport } from './routes/app.estok'
import { Route as AppFaktirasyonRouteImport } from './routes/app.faktirasyon'
import { Route as AppKesRouteImport } from './routes/app.kes'
import { Route as AppRapoRouteImport } from './routes/app.rapo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const EnskripsyonRoute = EnskripsyonRouteImport.update({
  id: '/enskripsyon',
  path: '/enskripsyon',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEstokRoute = AppEstokRouteImport.update({
  id: '/estok',
  path: '/estok',
  getParentRoute: () => AppRoute,
} as any)
const AppFaktirasyonRoute = AppFaktirasyonRouteImport.update({
  id: '/faktirasyon',
  path: '/faktirasyon',
  getParentRoute: () => AppRoute,
} as any)
const AppKesRoute = AppKesRouteImport.update({
  id: '/kes',
  path: '/kes',
  getParentRoute: () => AppRoute,
} as any)
const AppRapoRoute = AppRapoRouteImport.update({
  id: '/rapo',
  path: '/rapo',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/enskripsyon': typeof EnskripsyonRoute
  '/login': typeof LoginRoute
  '/app/estok': typeof AppEstokRoute
  '/app/faktirasyon': typeof AppFaktirasyonRoute
  '/app/kes': typeof AppKesRoute
  '/app/rapo': typeof AppRapoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enskripsyon': typeof EnskripsyonRoute
  '/login': typeof LoginRoute
  '/app/estok': typeof AppEstokRoute
  '/app/faktirasyon': typeof AppFaktirasyonRoute
  '/app/kes': typeof AppKesRoute
  '/app/rapo': typeof AppRapoRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/enskripsyon': typeof EnskripsyonRoute
  '/login': typeof LoginRoute
  '/app/estok': typeof AppEstokRoute
  '/app/faktirasyon': typeof AppFaktirasyonRoute
  '/app/kes': typeof AppKesRoute
  '/app/rapo': typeof AppRapoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/enskripsyon'
    | '/login'
    | '/app/estok'
    | '/app/faktirasyon'
    | '/app/kes'
    | '/app/rapo'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enskripsyon'
    | '/login'
    | '/app/estok'
    | '/app/faktirasyon'
    | '/app/kes'
    | '/app/rapo'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/enskripsyon'
    | '/login'
    | '/app/estok'
    | '/app/faktirasyon'
    | '/app/kes'
    | '/app/rapo'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  EnskripsyonRoute: typeof EnskripsyonRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enskripsyon': {
      id: '/enskripsyon'
      path: '/enskripsyon'
      fullPath: '/enskripsyon'
      preLoaderRoute: typeof EnskripsyonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estok': {
      id: '/app/estok'
      path: '/estok'
      fullPath: '/app/estok'
      preLoaderRoute: typeof AppEstokRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/faktirasyon': {
      id: '/app/faktirasyon'
      path: '/faktirasyon'
      fullPath: '/app/faktirasyon'
      preLoaderRoute: typeof AppFaktirasyonRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kes': {
      id: '/app/kes'
      path: '/kes'
      fullPath: '/app/kes'
      preLoaderRoute: typeof AppKesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rapo': {
      id: '/app/rapo'
      path: '/rapo'
      fullPath: '/app/rapo'
      preLoaderRoute: typeof AppRapoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEstokRoute: typeof AppEstokRoute
  AppFaktirasyonRoute: typeof AppFaktirasyonRoute
  AppKesRoute: typeof AppKesRoute
  AppRapoRoute: typeof AppRapoRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEstokRoute: AppEstokRoute,
  AppFaktirasyonRoute: AppFaktirasyonRoute,
  AppKesRoute: AppKesRoute,
  AppRapoRoute: AppRapoRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  EnskripsyonRoute: EnskripsyonRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
