/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as EnskripsyonRouteImport } from './routes/enskripsyon'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppEkipRouteImport } from './routes/app.ekip'
import { Route as AppEnpresyonRouteImport } from './routes/app.enpresyon'
import { Route as AppEnstitisyonRouteImport } from './routes/app.enstitisyon'
import { Route as AppEstokRouteImport } from './routes/app.estok'
import { Route as AppFaktirasyonRouteImport } from './routes/app.faktirasyon'
import { Route as AppFouniseRouteImport } from './routes/app.founise'
import { Route as AppKesRouteImport } from './routes/app.kes'
import { Route as AppOtelRouteImport } from './routes/app.otel'
import { Route as AppParametRouteImport } from './routes/app.paramet'
import { Route as AppRapoRouteImport } from './routes/app.rapo'
import { Route as AppTachRouteImport } from './routes/app.tach'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const EnskripsyonRoute = EnskripsyonRouteImport.update({
  id: '/enskripsyon',
  path: '/enskripsyon',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEkipRoute = AppEkipRouteImport.update({
  id: '/ekip',
  path: '/ekip',
  getParentRoute: () => AppRoute,
} as any)
const AppEnpresyonRoute = AppEnpresyonRouteImport.update({
  id: '/enpresyon',
  path: '/enpresyon',
  getParentRoute: () => AppRoute,
} as any)
const AppEnstitisyonRoute = AppEnstitisyonRouteImport.update({
  id: '/enstitisyon',
  path: '/enstitisyon',
  getParentRoute: () => AppRoute,
} as any)
const AppEstokRoute = AppEstokRouteImport.update({
  id: '/estok',
  path: '/estok',
  getParentRoute: () => AppRoute,
} as any)
const AppFaktirasyonRoute = AppFaktirasyonRouteImport.update({
  id: '/faktirasyon',
  path: '/faktirasyon',
  getParentRoute: () => AppRoute,
} as any)
const AppFouniseRoute = AppFouniseRouteImport.update({
  id: '/founise',
  path: '/founise',
  getParentRoute: () => AppRoute,
} as any)
const AppKesRoute = AppKesRouteImport.update({
  id: '/kes',
  path: '/kes',
  getParentRoute: () => AppRoute,
} as any)
const AppOtelRoute = AppOtelRouteImport.update({
  id: '/otel',
  path: '/otel',
  getParentRoute: () => AppRoute,
} as any)
const AppParametRoute = AppParametRouteImport.update({
  id: '/paramet',
  path: '/paramet',
  getParentRoute: () => AppRoute,
} as any)
const AppRapoRoute = AppRapoRouteImport.update({
  id: '/rapo',
  path: '/rapo',
  getParentRoute: () => AppRoute,
} as any)
const AppTachRoute = AppTachRouteImport.update({
  id: '/tach',
  path: '/tach',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/enskripsyon': typeof EnskripsyonRoute
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRoute
  '/app/ekip': typeof AppEkipRoute
  '/app/enpresyon': typeof AppEnpresyonRoute
  '/app/enstitisyon': typeof AppEnstitisyonRoute
  '/app/estok': typeof AppEstokRoute
  '/app/faktirasyon': typeof AppFaktirasyonRoute
  '/app/founise': typeof AppFouniseRoute
  '/app/kes': typeof AppKesRoute
  '/app/otel': typeof AppOtelRoute
  '/app/paramet': typeof AppParametRoute
  '/app/rapo': typeof AppRapoRoute
  '/app/tach': typeof AppTachRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enskripsyon': typeof EnskripsyonRoute
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRoute
  '/app/ekip': typeof AppEkipRoute
  '/app/enpresyon': typeof AppEnpresyonRoute
  '/app/enstitisyon': typeof AppEnstitisyonRoute
  '/app/estok': typeof AppEstokRoute
  '/app/faktirasyon': typeof AppFaktirasyonRoute
  '/app/founise': typeof AppFouniseRoute
  '/app/kes': typeof AppKesRoute
  '/app/otel': typeof AppOtelRoute
  '/app/paramet': typeof AppParametRoute
  '/app/rapo': typeof AppRapoRoute
  '/app/tach': typeof AppTachRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/enskripsyon': typeof EnskripsyonRoute
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRoute
  '/app/ekip': typeof AppEkipRoute
  '/app/enpresyon': typeof AppEnpresyonRoute
  '/app/enstitisyon': typeof AppEnstitisyonRoute
  '/app/estok': typeof AppEstokRoute
  '/app/faktirasyon': typeof AppFaktirasyonRoute
  '/app/founise': typeof AppFouniseRoute
  '/app/kes': typeof AppKesRoute
  '/app/otel': typeof AppOtelRoute
  '/app/paramet': typeof AppParametRoute
  '/app/rapo': typeof AppRapoRoute
  '/app/tach': typeof AppTachRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/enskripsyon'
    | '/login'
    | '/superadmin'
    | '/app/ekip'
    | '/app/enpresyon'
    | '/app/enstitisyon'
    | '/app/estok'
    | '/app/faktirasyon'
    | '/app/founise'
    | '/app/kes'
    | '/app/otel'
    | '/app/paramet'
    | '/app/rapo'
    | '/app/tach'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enskripsyon'
    | '/login'
    | '/superadmin'
    | '/app/ekip'
    | '/app/enpresyon'
    | '/app/enstitisyon'
    | '/app/estok'
    | '/app/faktirasyon'
    | '/app/founise'
    | '/app/kes'
    | '/app/otel'
    | '/app/paramet'
    | '/app/rapo'
    | '/app/tach'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/enskripsyon'
    | '/login'
    | '/superadmin'
    | '/app/ekip'
    | '/app/enpresyon'
    | '/app/enstitisyon'
    | '/app/estok'
    | '/app/faktirasyon'
    | '/app/founise'
    | '/app/kes'
    | '/app/otel'
    | '/app/paramet'
    | '/app/rapo'
    | '/app/tach'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  EnskripsyonRoute: typeof EnskripsyonRoute
  LoginRoute: typeof LoginRoute
  SuperadminRoute: typeof SuperadminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enskripsyon': {
      id: '/enskripsyon'
      path: '/enskripsyon'
      fullPath: '/enskripsyon'
      preLoaderRoute: typeof EnskripsyonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ekip': {
      id: '/app/ekip'
      path: '/ekip'
      fullPath: '/app/ekip'
      preLoaderRoute: typeof AppEkipRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/enpresyon': {
      id: '/app/enpresyon'
      path: '/enpresyon'
      fullPath: '/app/enpresyon'
      preLoaderRoute: typeof AppEnpresyonRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/enstitisyon': {
      id: '/app/enstitisyon'
      path: '/enstitisyon'
      fullPath: '/app/enstitisyon'
      preLoaderRoute: typeof AppEnstitisyonRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estok': {
      id: '/app/estok'
      path: '/estok'
      fullPath: '/app/estok'
      preLoaderRoute: typeof AppEstokRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/faktirasyon': {
      id: '/app/faktirasyon'
      path: '/faktirasyon'
      fullPath: '/app/faktirasyon'
      preLoaderRoute: typeof AppFaktirasyonRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/founise': {
      id: '/app/founise'
      path: '/founise'
      fullPath: '/app/founise'
      preLoaderRoute: typeof AppFouniseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kes': {
      id: '/app/kes'
      path: '/kes'
      fullPath: '/app/kes'
      preLoaderRoute: typeof AppKesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/otel': {
      id: '/app/otel'
      path: '/otel'
      fullPath: '/app/otel'
      preLoaderRoute: typeof AppOtelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/paramet': {
      id: '/app/paramet'
      path: '/paramet'
      fullPath: '/app/paramet'
      preLoaderRoute: typeof AppParametRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rapo': {
      id: '/app/rapo'
      path: '/rapo'
      fullPath: '/app/rapo'
      preLoaderRoute: typeof AppRapoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tach': {
      id: '/app/tach'
      path: '/tach'
      fullPath: '/app/tach'
      preLoaderRoute: typeof AppTachRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEkipRoute: typeof AppEkipRoute
  AppEnpresyonRoute: typeof AppEnpresyonRoute
  AppEnstitisyonRoute: typeof AppEnstitisyonRoute
  AppEstokRoute: typeof AppEstokRoute
  AppFaktirasyonRoute: typeof AppFaktirasyonRoute
  AppFouniseRoute: typeof AppFouniseRoute
  AppKesRoute: typeof AppKesRoute
  AppOtelRoute: typeof AppOtelRoute
  AppParametRoute: typeof AppParametRoute
  AppRapoRoute: typeof AppRapoRoute
  AppTachRoute: typeof AppTachRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEkipRoute: AppEkipRoute,
  AppEnpresyonRoute: AppEnpresyonRoute,
  AppEnstitisyonRoute: AppEnstitisyonRoute,
  AppEstokRoute: AppEstokRoute,
  AppFaktirasyonRoute: AppFaktirasyonRoute,
  AppFouniseRoute: AppFouniseRoute,
  AppKesRoute: AppKesRoute,
  AppOtelRoute: AppOtelRoute,
  AppParametRoute: AppParametRoute,
  AppRapoRoute: AppRapoRoute,
  AppTachRoute: AppTachRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  EnskripsyonRoute: EnskripsyonRoute,
  LoginRoute: LoginRoute,
  SuperadminRoute: SuperadminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
